const path = require('path')
const express = require('express')
const { signuRender, loginRender, homeRender, otpRender, signupPost, loginPost , verifyOtpPost, logoutRander, forgot, newpasswordRender, newpasswordPost ,newOTPvarify, newOTPRender } = require('../controllers')
const Router = express.Router()
const auth = require('../middleware/middleware')
Router.get('/' , signuRender )
Router.get('/login' , loginRender)
Router.get('/home' ,auth, homeRender)
Router.get('/newotpRander' , newOTPRender)
Router.get('/otp' , otpRender)
Router.get('/newPassword' , newpasswordRender)
Router.get('/logout', logoutRander)

Router.post('/users' , signupPost)
Router.post('/logined' , loginPost)
Router.post('/forgotpassword' , forgot)
Router.post('/varifyOTP' , verifyOtpPost)
Router.post('/newPasswordpost' ,newpasswordPost)
Router.post('/newotp', newOTPvarify)
 module.exports = Router